branches:
  only:
    - "master"

git:
  depth: 5

language: node_js

node_js:
  - "10"

sudo: required

services:
  - docker

before_install:
  - docker --version
  - docker build -t packagephobia .

script:
  - npm run test
