branches:
  only:
    - "master"

git:
  depth: 5

cache:
  directories:
    - node_modules

language: node_js

node_js:
  - "10"

before_install:
  - npm install -g npm
  - npm --version

script:
  - npm run build
  - npm run test
